# Generated by Django 4.1.7 on 2023-03-22 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PG_Facility_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'pg_facility_master',
            },
        ),
        migrations.CreateModel(
            name='PG_PostAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pg_name', models.CharField(max_length=50)),
                ('avail_status', models.BooleanField(default=False)),
                ('gender', models.CharField(max_length=15)),
                ('no_of_rooms', models.PositiveIntegerField()),
                ('occupacy', models.CharField(max_length=10)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('pg_type', models.CharField(max_length=15)),
                ('website', models.CharField(max_length=50, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='pg_profile_img_dir/')),
                ('instructions_docs', models.FileField(blank=True, null=True, upload_to='pg_instruct_file_dir/')),
                ('address', models.TextField()),
                ('street', models.TextField(null=True)),
                ('area', models.TextField()),
                ('city', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=15)),
                ('zipcode', models.CharField(max_length=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pg_post_ads',
            },
        ),
        migrations.CreateModel(
            name='PG_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pg_images', models.ImageField(blank=True, null=True, upload_to='pg_images_dir/')),
                ('pg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pg_main.pg_postads')),
            ],
            options={
                'db_table': 'pg_images',
            },
        ),
        migrations.CreateModel(
            name='PG_Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pg_main.pg_facility_master')),
                ('pg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pg_main.pg_postads')),
            ],
            options={
                'db_table': 'pg_facility',
            },
        ),
    ]
