# Generated by Django 4.1.7 on 2023-03-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg_main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pg_postads',
            name='gender',
        ),
        migrations.AddField(
            model_name='pg_postads',
            name='gender_preference',
            field=models.CharField(choices=[('select', 'select'), ('Boys', 'Boys'), ('Girls', 'Girls'), ('Both', 'Both')], default='select', max_length=15),
        ),
        migrations.AlterField(
            model_name='pg_postads',
            name='occupacy',
            field=models.CharField(choices=[('select', 'select'), ('Single-bed', 'Single-bed'), ('Double-bed', 'Double-bed'), ('Triple-bed', 'Triple-bed'), ('other', 'other')], default='select', max_length=10),
        ),
        migrations.AlterField(
            model_name='pg_postads',
            name='pg_type',
            field=models.CharField(choices=[('select', 'select'), ('Tenament', 'Tenament'), ('Appartment', 'Appartment'), ('Banglows', 'Banglows'), ('Rowhouse', 'Rowhouse'), ('Roofhouse', 'Roofhouse')], default='select', max_length=15),
        ),
    ]
