# Generated by Django 4.1.7 on 2023-03-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg_main', '0002_remove_pg_postads_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pg_postads',
            name='website',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
