# Generated by Django 4.1.7 on 2023-04-02 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pg_main', '0003_alter_pg_postads_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='PG_Facility_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac', models.BooleanField(default=False, null=True)),
                ('wifi', models.BooleanField(default=False, null=True)),
                ('laundry', models.BooleanField(default=False, null=True)),
                ('room_cleaning', models.BooleanField(default=False, null=True)),
                ('washing_machine', models.BooleanField(default=False, null=True)),
                ('full_water_supply', models.BooleanField(default=False, null=True)),
                ('food', models.BooleanField(default=False, null=True)),
                ('kitchen_appliances', models.BooleanField(default=False, null=True)),
                ('parking', models.BooleanField(default=False, null=True)),
                ('wardrobe', models.BooleanField(default=False, null=True)),
                ('furnished_room', models.BooleanField(default=False, null=True)),
                ('cctv_security', models.BooleanField(default=False, null=True)),
                ('pg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pg_main.pg_postads')),
            ],
        ),
    ]
