# Generated by Django 4.1.7 on 2023-04-02 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pg_main', '0005_pg_facility_new_attached_washroom'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PG_Facility_new',
            new_name='PG_Amenities',
        ),
        migrations.AlterModelTable(
            name='pg_amenities',
            table='pg_amenities',
        ),
    ]
