# Generated by Django 4.1.7 on 2023-04-14 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pg_main', '0006_rename_pg_facility_new_pg_amenities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PG_Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pg_main.pg_postads')),
            ],
            options={
                'db_table': 'pg_comments',
            },
        ),
    ]
