# Generated by Django 4.1.7 on 2023-04-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg_main', '0007_pg_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg_amenities',
            name='other',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pg_amenities',
            name='ac',
            field=models.BooleanField(default=False),
        ),
    ]
