# Generated by Django 4.1.7 on 2023-04-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg_main', '0008_pg_amenities_other_alter_pg_amenities_ac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pg_amenities',
            name='other',
            field=models.CharField(default='Other', max_length=20, null=True),
        ),
    ]
