# Generated by Django 4.1.7 on 2023-04-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg_main', '0009_alter_pg_amenities_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pg_amenities',
            name='attached_washroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pg_amenities',
            name='cctv_security',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pg_amenities',
            name='food',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pg_amenities',
            name='full_water_supply',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pg_amenities',
            name='furnished_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pg_amenities',
            name='kitchen_appliances',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pg_amenities',
            name='laundry',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pg_amenities',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pg_amenities',
            name='room_cleaning',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pg_amenities',
            name='wardrobe',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pg_amenities',
            name='washing_machine',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pg_amenities',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
    ]
